import {
  pgTable,
  serial,
  varchar,
  numeric,
  integer,
  date,
  uuid,
  timestamp,
} from "drizzle-orm/pg-core";

export const authUsers = pgTable("auth.users", {
  id: uuid("id").primaryKey(),
});

export const powerliftingResults = pgTable("powerlifting_results", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }),
  sex: varchar("sex", { length: 1 }),
  event: varchar("event", { length: 1 }),
  equipment: varchar("equipment", { length: 50 }),
  age: numeric("age", { precision: 4, scale: 1 }),
  ageClass: varchar("age_class", { length: 10 }),
  birthYearClass: varchar("birth_year_class", { length: 10 }),
  division: varchar("division", { length: 20 }),
  bodyweightkg: numeric("bodyweight_kg", { precision: 5, scale: 1 }),
  weightclasskg: varchar("weight_class_kg", { length: 10 }),
  squat1kg: numeric("squat1_kg", { precision: 5, scale: 1 }),
  squat2kg: numeric("squat2_kg", { precision: 5, scale: 1 }),
  squat3kg: numeric("squat3_kg", { precision: 5, scale: 1 }),
  squat4kg: numeric("squat4_kg", { precision: 5, scale: 1 }),
  best3squatkg: numeric("best3squat_kg", { precision: 5, scale: 1 }),
  bench1kg: numeric("bench1_kg", { precision: 5, scale: 1 }),
  bench2kg: numeric("bench2_kg", { precision: 5, scale: 1 }),
  bench3kg: numeric("bench3_kg", { precision: 5, scale: 1 }),
  bench4kg: numeric("bench4_kg", { precision: 5, scale: 1 }),
  best3benchkg: numeric("best3bench_kg", { precision: 5, scale: 1 }),
  deadlift1kg: numeric("deadlift1_kg", { precision: 5, scale: 1 }),
  deadlift2kg: numeric("deadlift2_kg", { precision: 5, scale: 1 }),
  deadlift3kg: numeric("deadlift3_kg", { precision: 5, scale: 1 }),
  deadlift4kg: numeric("deadlift4_kg", { precision: 5, scale: 1 }),
  best3deadliftkg: numeric("best3deadlift_kg", { precision: 5, scale: 1 }),
  totalkg: numeric("total_kg", { precision: 5, scale: 1 }),
  place: integer("place"),
  dots: numeric("dots", { precision: 6, scale: 2 }),
  wilks: numeric("wilks", { precision: 6, scale: 2 }),
  glossbrenner: numeric("glossbrenner", { precision: 6, scale: 2 }),
  goodlift: numeric("goodlift", { precision: 6, scale: 2 }),
  tested: varchar("tested", { length: 10 }),
  country: varchar("country", { length: 50 }),
  state: varchar("state", { length: 50 }),
  federation: varchar("federation", { length: 50 }),
  parentFederation: varchar("parent_federation", { length: 50 }),
  date: date("date"),
  meetCountry: varchar("meet_country", { length: 50 }),
  meetState: varchar("meet_state", { length: 50 }),
  meetTown: varchar("meet_town", { length: 50 }),
  meetName: varchar("meet_name", { length: 100 }),
  sanctioned: varchar("sanctioned", { length: 10 }),
});

export const profiles = pgTable("profiles", {
  id: uuid("id")
    .primaryKey()
    .references(() => authUsers.id),
  first_name: varchar("first_name").notNull(),
  last_name: varchar("last_name").notNull(),
  role: varchar("role").default("user").notNull(),
  avatar_url: varchar("avatar_url"),
  created_at: timestamp("created_at").defaultNow().notNull(),
});
